Рефакторинг доманной чати.
Perbudag/PetFamily pull request #10
Opened 2024-09-07 15:44 UTC by Perbudag

Добавление классов команды добавления волонтера.
Добавление репозитория волонтера.

2024-09-08 08:29 UTC, YaraOduvanchik requested changes

2024-09-08 08:29 UTC, YaraOduvanchik commented on PetFamily.Backend/src/PetFamily.Application/Commands/Volunteer/Create/CreateVolunteerCommand.cs
> +            int PetsOnTreatmentCount,
PetsFoundHomeCount, PetsLookingForHomeCount и PetsOnTreatmentCount ненужно передавать, это должны быть не поня, а методы в доменной модели волонтёра

2024-09-08 08:29 UTC, YaraOduvanchik commented on PetFamily.Backend/src/PetFamily.Infrastructure/CommandHandlers/VolunteerCommands/CreateVolunteerHandler.cs
> +        private readonly IVolunteerRepositoriy repositoriy;
Лучше назвать _repositoriy

2024-09-08 08:29 UTC, YaraOduvanchik commented on PetFamily.Backend/src/PetFamily.Infrastructure/CommandHandlers/VolunteerCommands/CreateVolunteerHandler.cs
> +            this.repositoriy = repositoriy;
И тут лучше убрать this, после того как переименуешь поле repositoriy в _repositoriy

2024-09-08 08:29 UTC, YaraOduvanchik commented on PetFamily.Backend/src/PetFamily.Infrastructure/CommandHandlers/VolunteerCommands/CreateVolunteerHandler.cs
> +                socialNetworks.Select(x => x.Value).ToList(),
Тут вот это: ненужно .Select(x => x.Value).ToList()

2024-09-08 08:29 UTC, YaraOduvanchik commented on PetFamily.Backend/src/PetFamily.Infrastructure/CommandHandlers/VolunteerCommands/CreateVolunteerHandler.cs
> +                requisites.Select(x => x.Value).ToList(),
тут тоже

2024-09-08 18:57 UTC, Perbudag commented
Я передаю лист в SocialNetworks и Requisites потому, что они являются ValueObjectList<T>. Я не могу перегрузить оператор присваивания на IEnumerable, так как на интерфейсы такая перегрузка невозможна.

2024-09-09 03:52 UTC, YaraOduvanchik approved these changes

2024-09-09 06:07 UTC, merged