Добавлена возможность сохранять файлы в minio.
Perbudag/PetFamily pull request #18
Opened 2024-09-29 12:25 UTC by Perbudag

2024-09-29 16:58 UTC, KirillSachkov requested changes
У тебя есть лишние файлы, которые должны находится в гитигноре, папка v17 например

2024-09-29 16:58 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
> +                var fileData = new FileData(formFile.OpenReadStream(), location);
Когда ты открываешь поток на чтение обязательно нужно вызывать using, чтобы закрыть его через Dispose. Так нельзя делать, всегда неуправляемые ресурсы нужно закрывать через автоматический или ручной вызов Dispose

2024-09-29 16:58 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
> +                var fileData = new FileData(formFile.OpenReadStream(), location);
В дальнейших занятиях я показывал как это делать красиво

2024-09-29 16:58 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
> +            await batchTask.Run();
Никогда не используй так асинхронность, нужно обязательно вызывать await

2024-09-29 16:58 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
> +            await batchTask.Run();
https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#async-all-the-way

2024-09-30 08:04 UTC, KirillSachkov requested changes

2024-09-30 08:04 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
>              });
Зачем здесь делать OnExecuted? Если ты вызваешь await, то ты в любом случае дождешься, когда у тебя метод выполнится и дальше ты спокойно можешь работать с его результатом. Далее зачем ниже вызывать batchTask.Run(), когда ты с помощью await уже вызываешь этот метод

2024-09-30 08:31 UTC, Perbudag commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
>              });
BatchTask это мой собственный класс, созданный для удобной, пакетной загрузки файлов. В конструктор он принимает список Task-ов и количество Task-ов, которые могут работать одновременно. В OnExecuted передается Action<T>, который будет выполнен после завершения работы каждого Task-а, а T это тип данных, который возвращает Task. Run - это функция, которая запускает работу Task-ов. Я сделал этот класс, для того, чтобы можно было сохранять пути к файлу сразу же как они будут загружены в minio. 
Вот как это должно работать:
 1) Вызываем функцию fileProvider.Upload и получаем BatchTask<Result<string>>.
 2) Добавляем в BatchTask.OnExecuted функцию следующего вида:
```
 BatchTask.OnExecuted(fileName =>  
            {
                if(fileName.IsSuccess)
                {
                    // Сохраняем название файла в бд
                }
                else
                {
                    // Выводим ошибку
                }
            });
```
3) Вызываем BatchTask.Run()
Таким образом название файла будет сохранено сразу же после загрузки файла и если, к примеру, пользователь решит закрыть браузер после загрузки половины файлов, те файлы, которые уже загружены в minio будут сохранены и в базу данных и нам не придется их удалять.

Если тебе все еще не понятно как у меня реализована загрузка файлов, посмотри реализацию класса BatchTask.

2024-09-30 08:39 UTC, KirillSachkov commented on PetFamily.Backend/src/PetFamily.API/Controllers/FileController.cs
>              });
Увидел, потерял из виду BatchTask) Тогда всё ок

2024-09-30 08:39 UTC, KirillSachkov approved these changes

2024-09-30 09:36 UTC, merged