Добавлены классы Species и Breed.
Perbudag/PetFamily pull request #9
Opened 2024-09-02 18:09 UTC by Perbudag

Добавлены свойства SpeciesId и BreedId в класс AppearanceDetails.
Добавлено свойство DbSet<Species> Species в DbContext. 
Изменена конфигурация DbContext.

2024-09-02 18:24 UTC, YADARAN1 requested changes

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Entities/Breed.cs
> +        public Breed() : base(BreedId.NewId()) { }
public Breed(BreedId) : base(id)

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Entities/Breed.cs
> +        public Breed(string name) : base(BreedId.NewId())
public Breed(BreedId id, string name) : base(id)

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Entities/Breed.cs
> +        public static Result<Breed> Create(string name)
И создаёшь Id вместе с названием

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Entities/Breed.cs
> +            var species = new Breed(name);
почему тут вид, когда ты создаёшь породу

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Species.cs
> +        public Species() : base(SpeciesId.NewId()) { }
Тут тоже самое

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Species.cs
> +        public Species(string name, List<Breed> breeds) : base(SpeciesId.NewId())
и здесь

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Domain/SpeciesAggregate/Species.cs
> +        public static Result<Species> Create(string name, List<Breed> breeds)
И тут

2024-09-02 18:24 UTC, YADARAN1 commented on PetFamily.Backend/src/PetFamily.Infrastructure/Database/Configurations/SpeciesConfiguration.cs
> +                .OnDelete(DeleteBehavior.Cascade);
удаляя вид, не нужно удалять породу

2024-09-02 18:36 UTC, Perbudag commented
Почему я должен передавать в Species и Breed id при создании, чем они отличаются от Volunteer и Pet? Кстати конструкторы должны быть приватными, я их изменю.

2024-09-02 18:39 UTC, Perbudag commented
Разве у разных видов может быть одна порода? Не логично ли, что все породы конкретного вида удаляются при удалении вида?

2024-09-02 18:49 UTC, YADARAN1 commented
Отвечаю на первый комментарий:

Контроль над идентификатором. Если идентификатор создается автоматически внутри конструктора, то ты теряешь возможность передать уже существующий идентификатор. Это может быть важно, например, при восстановлении объектов из базы данных или других хранилищ, где идентификатор уже задан

В будущем Кирилл покажет, что такое SoftDelete и это всё равно придётся переделать

2024-09-02 18:52 UTC, YADARAN1 commented
Отвечаю на второй комментарий:

![image](https://github.com/user-attachments/assets/85b63c6b-a740-4ff3-8e10-e54fad8a66b9)
Здесь ошибка, ещё раз перепроверил, тут у тебя должен быть не VO BreedId, а GuidBreedId, перечитай ещё раз задание.

Именно должен быть Guid, потому что это ссылка на сущность в другом агрегате, а такой VO оно не должно быть, поэтому мы не на id ссылаемся, а на guid и через вид будем получать породу

2024-09-02 18:59 UTC, Perbudag commented
> Отвечаю на первый комментарий:
> 
> Контроль над идентификатором. Если идентификатор создается автоматически внутри конструктора, то ты теряешь возможность передать уже существующий идентификатор. Это может быть важно, например, при восстановлении объектов из базы данных или других хранилищ, где идентификатор уже задан
> 
> В будущем Кирилл покажет, что такое SoftDelete и это всё равно придётся переделать

Можно мне решать проблемы по мене их появления? Я еще не прошел тему с SoftDelete. Если мне будет нужно изменить код в будущем, то я это сделаю.

2024-09-02 19:00 UTC, Perbudag commented
> Отвечаю на первый комментарий:
> 
> ![image](https://private-user-images.githubusercontent.com/130922485/363774803-85b63c6b-a740-4ff3-8e10-e54fad8a66b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDM4ODMsIm5iZiI6MTcyNTMwMzU4MywicGF0aCI6Ii8xMzA5MjI0ODUvMzYzNzc0ODAzLTg1YjYzYzZiLWE3NDAtNGZmMy04ZTEwLWU1NGZhZDhhNjZiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxODU5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDFjNDljMTgwNDVhODQ0NGIyZTJkNmU1YzE2ZWUxOGIyNTBhMjg5NTkwZjQ0M2ZiZWQ0NmQ2NTA3NTNiN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9aN7QrWJIIG9YIyzpOzbLzdi6k7wpB5hSunfKOh5npA) Здесь ошибка, ещё раз перепроверил, тут у тебя должен быть не VO BreedId, а GuidBreedId, перечитай ещё раз задание.
> 
> Именно должен быть Guid, потому что это ссылка на сущность в другом агрегате, а такой VO оно не должно быть, поэтому мы не на id ссылаемся, а на guid и через вид будем получать породу

Но ведь BreedId по сути и является Guid, просто обернутый в класс.

2024-09-02 19:05 UTC, YADARAN1 commented
Отвечаю на второй комментарий:

Допустим такая ситуация, у нас у 1 вида может быть несколько разных пород, то получается мы удалим нужную нам породу с БД

2024-09-02 19:06 UTC, YADARAN1 commented
Отвечая на ответ(научи как отвечать на комментарии, буду благодарен)

Хорошо, оставь как есть, потом отрефакторишь

2024-09-02 19:07 UTC, Perbudag commented
![Screenshot_1](https://github.com/user-attachments/assets/eff52b97-4c96-47da-8055-9c07a08bad3d)

> Отвечая на ответ(научи как отвечать на комментарии, буду благодарен)
> 
> Хорошо, оставь как есть, потом отрефакторишь

![Screenshot_1](https://github.com/user-attachments/assets/3484575a-a93d-4a88-bce9-163aec70f842)

2024-09-02 19:08 UTC, YADARAN1 commented
> Отвечаю на второй комментарий:
> 
> Допустим такая ситуация, у нас у 1 вида может быть несколько разных пород, то получается мы удалим нужную нам породу с БД

Можешь оставить каскадное удаление, потом по мере поступления проблем это можно решить

2024-09-02 19:10 UTC, Perbudag commented
такс, получается проблемы только с публичными конструкторами?

2024-09-02 19:10 UTC, YADARAN1 commented
> такс, получается проблемы только с публичными конструкторами?

И BreedId, измени его на Guid

2024-09-02 19:11 UTC, YADARAN1 commented
И ещё в породе ты создаёшь species, там название переменной поменяй

2024-09-02 19:11 UTC, Perbudag commented
> > такс, получается проблемы только с публичными конструкторами?
> 
> И BreedId, измени его на Guid

Я все еще не понимаю зачем менять BreedId на Guid.

2024-09-03 06:39 UTC, YADARAN1 approved these changes

2024-09-03 06:41 UTC, merged